name: CI/CD Deployment to GKE

on: 
    push:
        branches:
            - main

env:
    PROJECT_ID:  ${{ secrets.GCP_PROJECT_ID }}
    GKE_CLUSTER: ${{ secrets.my_cluster }}
    GKE_REGION: "europe-west4"
    DEPLOYMENT_NAME: "mlops-app"
    REPOSITORY: "europe-west3-docker.pkg.dev/delta-spark-468711-t2/my-repo"
    IMAGE: "europe-west3-docker.pkg.dev/delta-spark-468711-t2/my-repo/mlops-app"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        container: 
            image: google/cloud-sdk:latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
            
            - name: Configure GCloud
              run: |
                   gcloud config set peoject $PROJECT_ID
                   gcloud auth configure-docker europe-west3-docker.pkg.dev

            - name: Building and Pushing Image
              run: |
                  docker build -t $IMAGE:$GITHUB_SHA .
                  docker push $IMAGE:$GITHUB_SHA

            - name: GKE configuration
              run: |
                  gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

            - name: Deploying to Kubernetes
              run: |
                 kubectl apply -f kubernetes-deployment.yaml
                 kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA

              