name: CI/CD Deployment to GKE

on: 
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: "my-cluster"
  GKE_REGION: "europe-west4"
  DEPLOYMENT_NAME: "mlops-app"
  REPOSITORY: "europe-west3-docker.pkg.dev/delta-spark-468711-t2/my-repo"
  IMAGE: "europe-west3-docker.pkg.dev/delta-spark-468711-t2/my-repo/mlops-app"
  USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE auth plugin
        run: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
            sudo apt-get update
            sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure GCloud Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and Push Image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes-deployment.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA
